accu163 Beginning of work
TerebDan/DevOps-Trainee pull request #11
Opened 2022-07-28 18:46 UTC by TerebDan

2022-08-02 18:39 UTC, TerebDan commented on accu163/roles/APP_django/tasks/main.yml
> +    virtualenv_python: python2
There are no steps to start the server. The server is started manually.

2022-08-04 13:48 UTC, Neve requested changes
DB playbook overall:
if you are using community playbooks, please make sure to remove all unsupported platforms and features to keep codebase clean

2022-08-04 13:48 UTC, Neve commented on accu163/group_vars/Deploy
> +ansible_ssh_pass                : 1234
Do not store passwords in public repos, please use gitignore

2022-08-04 13:48 UTC, Neve commented on accu163/roles/APP_django/tasks/main.yml
> +  register: result
next time please be more specific in naming variables

2022-08-04 13:48 UTC, Neve commented on accu163/roles/DB/.github/stale.yml
> +# Configuration for probot-stale - https://github.com/probot/stale
Do we actually need this file in  the PR?

2022-08-04 13:48 UTC, Neve commented on accu163/roles/DB/.github/stale.yml
> +# Configuration for probot-stale - https://github.com/probot/stale
please add .github folder to gitignore

2022-08-04 13:48 UTC, Neve commented on accu163/roles/DB/molecule/default/converge.yml
> +---
either introduce molecule or remove tests from the playbook level

2022-08-04 13:48 UTC, Neve commented on accu163/roles/LB/files/nginx.conf
> +            proxy_pass http://192.168.0.141:8000;
please use variables instead of hardcode

2022-08-04 13:48 UTC, Neve commented on accu163/roles/LB/files/nginx.conf
> +            proxy_pass http://192.168.0.141:8000;
convert this config to j2 template, see my.cnf as example

2022-08-04 13:48 UTC, Neve commented on accu163/roles/LB/meta/main.yml
> +galaxy_info:
consider removing since there is no plans for ansible galaxy

2022-08-04 13:48 UTC, Neve commented on accu163/roles/LB/tasks/main.yml
> +  ansible.builtin.file:
use template instead of replacing the file

2022-08-04 13:48 UTC, Neve commented on accu163/roles/LB/tests/inventory
> +localhost
consider removing

2022-08-04 13:48 UTC, Neve commented on accu163/roles/LB/tests/test.yml
> +---
consider removing

2022-08-10 14:29 UTC, Neve approved these changes

2022-08-10 14:30 UTC, merged